---
ID: "6b65c802-eb79-493f-be8e-beff6b40b899"
Parent: "fbc36d10-ab8d-4173-936d-e1b875638062"
Template: "fbc36d10-ab8d-4173-936d-e1b875638062"
Path: /sitecore/templates/Feature/ACR/Facility Search/Facility Search Seal/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240530T201244Z
    - ID: "3ab3ff70-891f-4a86-a631-402500703852"
      Hint: code
      Value: $name
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b19d68c6-3030-4c5e-9c62-cdb786d61575"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240530T201247Z
